#define COMBO_TERM 45

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "EMvx5/yoEoBn"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 6
#define COMBO_SHOULD_TRIGGER
#define IDLE_TIMEOUT_MS 120

#define RGB_MATRIX_STARTUP_SPD 60

